name: Check SSM Release

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
    #- cron: "*/5 * * * *" uncomment for debug (every 5 min)

jobs:
  check_release:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: get latest Amazon SSM release
      id: get_latest_ssm_release
      run: |
        ssm_version=$(curl --silent https://api.github.com/repos/aws/amazon-ssm-agent/releases/latest | jq -r .tag_name)
        echo ::set-output name=ssm_version::${ssm_version}
        echo ::debug::ssm "latest release ${ssm_version}"
    
    - uses: actions/checkout@v3

    - name: tag repository with latest ssm version if needed
      id: tag_repository
      if: steps.get_latest_tag.outputs.tag != steps.get_latest_ssm_release.outputs.ssm_version
      uses: rickstaa/action-create-tag@v1
      with:
        force_push_tag: false
        tag_exists_error: false
        tag: ${{ steps.get_latest_ssm_release.outputs.ssm_version }}
